version: '1.20'
services:
  db:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - internal
  
  images: 
    image: images
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "9000:8080"
    networks:
      - internal

networks:
  internal: